import Head from "next/head";

import { Main, ContentLinks } from "./styles";

import PreviewLink from "../components/PreviewLink";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>Preview Link</h1>

        <ContentLinks>
          <PreviewLink name="Strip" link="https://stripe.com/" />
          <PreviewLink name="NextJs" link="https://nextjs.org/" />
          <PreviewLink name="ReactJs" link="https://reactjs.org/" />
          <PreviewLink name="Flutter" link="https://flutter.dev/" />
        </ContentLinks>
      </Main>
    </div>
  );
};
export default Home;
