import Head from "next/head";

import Preview from "../module/Preview";
const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Preview />
    </div>
  );
};
export default Home;
